set(_CATKIN_CURRENT_PACKAGE "bhand_controller")
set(bhand_controller_VERSION "0.1.2")
set(bhand_controller_MAINTAINER "Román Navarro <rnavarro@robotnik.es>, Jorge Ariño <jarino@robotnik.es>")
set(bhand_controller_PACKAGE_FORMAT "1")
set(bhand_controller_BUILD_DEPENDS "rospy" "std_msgs" "genmsg" "sensor_msgs" "geometry_msgs")
set(bhand_controller_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "genmsg" "sensor_msgs" "geometry_msgs")
set(bhand_controller_BUILDTOOL_DEPENDS "catkin")
set(bhand_controller_BUILDTOOL_EXPORT_DEPENDS )
set(bhand_controller_EXEC_DEPENDS "rospy" "std_msgs" "genmsg" "sensor_msgs" "geometry_msgs")
set(bhand_controller_RUN_DEPENDS "rospy" "std_msgs" "genmsg" "sensor_msgs" "geometry_msgs")
set(bhand_controller_TEST_DEPENDS )
set(bhand_controller_DOC_DEPENDS )
set(bhand_controller_URL_WEBSITE "http://wiki.ros.org/bhand_controller")
set(bhand_controller_URL_BUGTRACKER "https://github.com/RobotnikAutomation/barrett_hand/issues")
set(bhand_controller_URL_REPOSITORY "https://github.com/RobotnikAutomation/barrett_hand.git")
set(bhand_controller_DEPRECATED "")